import Head from "next/head";
import Layout from "../components/Layout";
import headshot from "../../public/images/profile/headshotBig.png";
import dev from "../../public/images/profile/developer-pic-1.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0 ">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={headshot}
                alt="MounirKanane"
                // className="rounded-lg border-1 border-gray-300 shadow-lg  h-auto w-3/4"
                // className="rounded-full shadow-lg w-2/3 h-auto"
                className="rounded-lg shadow-lg  w-3/4 h-auto"
              />
            </div>
              <div className="w-1/2 flex flex-col items-center self-center">
                <AnimatedText text="Engineering Scalable Solutions With Code" className="!text-7xl !text-left" /> 
                  <p>
                    As a skilled full-stack developer, I am dedicated to turning
                    ideas into innovative web applications. Explore my latest
                    projects and articles, showcasing my expertise in React.js
                    and web development.
                  </p>
              </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
